DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS  users (
  id bigint generated by default as identity,
  address_line_one varchar(255) not null,
  address_line_two varchar(255),
  country varchar(255) not null,
  date_last_view timestamp,
  email varchar(255) not null,
  name varchar(255) not null,
  phone_number_1 varchar(255),
  phone_number_2 varchar(255),
  phone_number_3 varchar(255),
  postal_code varchar(255),
  town_city varchar(255) not null,
  primary key (id)
);